config/routes.rb
Rails.application.routes.draw do
  resources :list_items
  root 'list_items#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list_item.rb
class ListItem < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello, world!"
  end
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  before_action :set_list_item, only: [:show, :edit, :update, :destroy]

  # GET /list_items
  # GET /list_items.json
  def index
    @list_items = ListItem.all
  end

  # GET /list_items/1
  # GET /list_items/1.json
  def show
  end

  # GET /list_items/new
  def new
    @list_item = ListItem.new
  end

  # GET /list_items/1/edit
  def edit
  end

  # POST /list_items
  # POST /list_items.json
  def create
    @list_item = ListItem.new(list_item_params)

    respond_to do |format|
      if @list_item.save
        format.html { redirect_to @list_item, notice: 'List item was successfully created.' }
        format.json { render :show, status: :created, location: @list_item }
      else
        format.html { render :new }
        format.json { render json: @list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /list_items/1
  # PATCH/PUT /list_items/1.json
  def update
    respond_to do |format|
      if @list_item.update(list_item_params)
        format.html { redirect_to @list_item, notice: 'List item was successfully updated.' }
        format.json { render :show, status: :ok, location: @list_item }
      else
        format.html { render :edit }
        format.json { render json: @list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /list_items/1
  # DELETE /list_items/1.json
  def destroy
    @list_item.destroy
    respond_to do |format|
      format.html { redirect_to list_items_url, notice: 'List item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list_item
      @list_item = ListItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_item_params
      params.require(:list_item).permit(:item, :details, :deadline, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>To Do List</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  <div class="container">
	    <%= yield %>
	  </div>
  </body>
</html>

app/views/list_items/_form.html.erb
<%= form_with(model: list_item, local: true) do |form| %>
  <% if list_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list_item.errors.count, "error") %> prohibited this list_item from being saved:</h2>

      <ul>
      <% list_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item %>
    <%= form.text_field :item, id: :list_item_item %>
  </div>

  <div class="field">
    <%= form.label :details %>
    <%= form.text_area :details, id: :list_item_details %>
  </div>

  <div class="field">
    <%= form.label :deadline %>
    <%= form.date_select :deadline, id: :list_item_deadline %>
  </div>

  <div class="field">
    <div class="field">
    <%= form.label :completed %>
    <%= form.check_box :completed, id: :list_item_completed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/list_items/edit.html.erb
<h1>Editing List Item</h1>

<%= render 'form', list_item: @list_item %>

<%= link_to 'Show', @list_item %> |
<%= link_to 'To Do List', list_items_path %>

app/views/list_items/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h1>To Do List</h1>

  <table class="table">
    <thead>
      <tr>
        <th class="col-md-3">Item</th>
        <th class="col-md-3">Deadline</th>
        <th class="col-md-3">Completed</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @list_items.each do |list_item| %>
           <% if list_item.deadline < DateTime.now %>
              <tr class="red">
           <% else %>
              <tr>
           <% end %>
         
              <td><%= list_item.item %></td>
              <td><%= list_item.deadline %></td>
              <td><%= list_item.completed %></td>
              <td class="col-md-1">
              <%= link_to 'Show', list_item %> <%= link_to 'Edit', edit_list_item_path(list_item)%>
              </td>
              <td>  
              <%= link_to 'Destroy', list_item, method: :delete, data: { confirm: 'Are you sure?' } %>
              </td>

              </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to "New List Item", new_list_item_path, class: "btn btn-sm btn-primary" %>

</div>

<div class="float-right">

  <span class="pull-right"><%= link_to "@belozi", 'http://belozi.com' %></span>

</div>

app/views/list_items/new.html.erb
<h1>New List Item</h1>

<%= render 'form', list_item: @list_item %>

<%= link_to 'To Do List', list_items_path %>

app/views/list_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @list_item.item %>
</p>

<p>
  <strong>Details:</strong>
  <%= @list_item.details %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @list_item.deadline %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @list_item.completed %>
</p>

<%= link_to 'Edit', edit_list_item_path(@list_item) %> |
<%= link_to 'To Do List', list_items_path %>